### PR TITLE
Integrating token-2022 standard into the program

### PR DESCRIPTION
**Pull request by topeolatunji19**
We have introduced changes to incorporate the new Token-2022 standard for `spl-tokens` into our codebase. These changes bring additional functionalities, such as fee calculations, to ensure accurate payments for transactions involving tokens adhering to the Token-2022 standard.

More details are available in the `token2022.md` file

### CODE REVIEW

**Comment by cloakd** [comment]
Any movement on this gents? Would love to get it merged in so we can build on top with FluxBeam

**Comment by cloakd** [comment]
Changes made RE TG Discussion, lets get this merged :)

**Comment by skrrb** [comment]
looking at the proposed changes, i don't think that the fee calculations are correct.

Lets assume that the mint is configured to have a 1000 bps fee with no max cap, and that one user wants to deposit 100 lamports. With these numbers, we have that in the deposit ix (https://github.com/alphabatem/openbook-v2/blob/master/programs/openbook-v2/src/instructions/deposit.rs#L23) `base_amount = 100` & `base_actual_amount = 90` (calculated with `post_fee_amount` helper fn in token_utils.rs)

During the transfer, `base_actual_amount` is used, while for the user `base_amount` is locked. This means that with the above fee config, 90 lamports are being transferred to the market (being the fee 9). Consequently, the market vault will end up with only 81 lamports, while in the user open orders 100 lamports are being tracked!

Although the proposed changes don't break the current tests, no new case has been added to verify that everything works as expected. In addition, the fuzz tests have not been updated to the new interfaces; `just fuzz` throws some errors

**Comment by anselsol** [comment]
Hello everyone! How can I help push this through the finish line?

**Comment by binyebarwe** [comment]
I guess you are joking @PurpleSquirrelMedia Obviously no merge if tests and fuzzy tests are failing

**Comment by staccDOTsol** [comment]
sorry is this blocked cuz you just need to double this?

```if let Ok(transfer_fee_config) = source_mint.get_extension::<TransferFeeConfig>() {
                transfer_fee_config
                    .newer_transfer_fee
                    .calculate_post_fee_amount(amount)
            } else {
                Some(amount)
            }```

**Comment by mschneider** [comment]
hey sorry this PR doesn't meet our standard for a contribution, will close this now

**Pull request closed without merging**
