### PR TITLE
program: update to anchor 0.29 and solana 1.17

### PR DESCRIPTION
**Pull request by farnyser**

### CODE REVIEW

**Comment by skrrb** [comment]
is this (besides solana 1.17) the same as #218?

**Comment by farnyser** [comment]
Basically yes, but also starting from latest master branch. 
Just pushed a rewrite so that it start from the (updated) #218 PR

**Comment by skrrb** [comment]
nice, so I will close the other one in favor of this since it's more complete.

PS: looks like you got latest switchboard + fuzz to work? that's great! i wasted a lot of time trying to put them together...

**Comment by farnyser** [comment]
I didn't let the fuzz run for a long time yet, but do far no issue :+1:

**Review by skrrb — APPROVED** [review]
lgtm

**Pull request merged**
